-- MySQL Workbench Synchronization
-- Generated: 2022-07-11 23:24
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Gabriel Evangelista

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `d-buggy_db`.`tickets` 
DROP FOREIGN KEY `fk_tickets_priority1`;

ALTER TABLE `d-buggy_db`.`tickets` 
ADD CONSTRAINT `fk_tickets_priority1`
  FOREIGN KEY (`priority_priority_id`)
  REFERENCES `d-buggy_db`.`priority` (`priority_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
